make: use gotestsum for tests
kcp-dev/kcp pull request #1156
Opened 2022-05-26 18:53 UTC by stevekuznetsov

This utility brings a lot of user-experience benefits to testing, as
well as emitting nice jUnit XML files that publish the output of our
tests for consumption by structured CI displays.

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

2022-05-26 20:56 UTC, ncdc requested changes
At least for local development (if not in CI too), could you please install gotestsum via the `$(GO_INSTALL)` convention we are using elsewhere in the Makefile?

2022-05-26 20:56 UTC, ncdc commented on Makefile
> +	 gotestsum $(GOTESTSUM_ARGS) -- -race -count $(COUNT) -coverprofile=coverage.txt -covermode=atomic $(TEST_ARGS) $$(go list "$(WHAT)" | grep -v ./test/e2e/)
Indentation is a little off?

2022-05-26 21:28 UTC, ncdc commented
Note, this makes it so `make test TEST_ARGS=-v` (verbose test output) doesn't work any more. You instead have to do `make test GOTESTSUM_ARGS='-f standard-verbose'`. I'm ok with that, but it was unexpected. Anyone feel strongly against this? @sttts

2022-05-26 23:55 UTC, ncdc approved these changes

2022-05-26 23:55 UTC, merged

2022-06-03 21:01 UTC, stevekuznetsov commented
Part of #324