Workspaces: Keep already-set owner annotations
kcp-dev/kcp pull request #1384
Opened 2022-06-28 14:46 UTC by davidfestal

## Summary

This PR allows keeping an already-set `owner` annotation on workspace creation, when it has been set by a `system:masters` user.

## Related issue(s)

This is related to required cleanup of obsolete parts in the `workspaces` virtual workspace to prepare for the Home workspace implementation.

2022-06-28 15:42 UTC, stevekuznetsov requested changes
I don't think we should be allowing people to provide this annotation - it's a system internal and can change at any time, getting clients to depend on it is bad. Why not impersonate or create a virtual endpoint for this?

2022-06-28 15:50 UTC, davidfestal commented
> I don't think we should be allowing people to provide this annotation - it's a system internal and can change at any time, getting clients to depend on it is bad. Why not impersonate or create a virtual endpoint for this?

It's not allowing *people*, but allowing users in the `system:masters` group, especially allowing the `workspaces` virtual workspace to set this annotation.
@sttts proposed this as a way to avoid impersonation from the `workspaces` virtual workspace side.

2022-06-28 16:38 UTC, stevekuznetsov commented
IMHO this will come back to bite us. This is not an API. At the minimum if we must do this, please parse the existing annotation and make sure it is valid JSON and deserializes into user info as expected.

2022-06-28 16:41 UTC, davidfestal commented
>At the minimum if we must do this, please parse the existing annotation and make sure it is valid JSON and deserializes into user info as expected.
Sure, I'll do that @stevekuznetsov

2022-06-28 19:34 UTC, davidfestal commented
> > At the minimum if we must do this, please parse the existing annotation and make sure it is valid JSON and deserializes into user info as expected.
> > Sure, I'll do that @stevekuznetsov

Done in commit https://github.com/kcp-dev/kcp/pull/1384/commits/3c46b23c3ac7f8f4dc28659db563f13744d2263e

2022-06-28 20:02 UTC, sttts commented
It's the workspace VW. There cannot be anything more internal qualified to set internal workspace annotations than this.

2022-06-29 06:55 UTC, s-urbaniak commented on pkg/admission/clusterworkspacetypeexists/admission.go
> +			cw.Annotations[tenancyv1alpha1.ClusterWorkspaceOwnerAnnotationKey] = string(rawInfo)
https://github.com/kcp-dev/kcp/blob/main/pkg/admission/reservedmetadata/admission.go

2022-06-29 07:00 UTC, sttts commented
1. please move this into its own admission plugin. Having it there is wrong, and super hard to understand what's going on.
2. the owner MUST be verified in the corresponding Validate method. If it is not, please add it.
3. if validate checks the correctness, then @s-urbaniak can exclude this annotation from those that are protected.

🔴 These are blockers for moving forward.

2022-07-15 15:12 UTC, davidfestal commented
@sttts Did you already fixed this in another PR ? Should this one be closed ?

2022-07-15 15:22 UTC, sttts commented
> @sttts Did you already fixed this in another PR ? Should this one be closed ?

yes. Will resume work on monday.

2022-07-20 06:32 UTC, closed without merging