📖 docs/../developers: describe metrics gathering for e2e tests
kcp-dev/kcp pull request #2840
Opened 2023-02-22 14:35 UTC by s-urbaniak

## Summary
This describes how to inspect and gather Prometheus metrics for e2e test runs.

## Related issue(s)

Fixes https://github.com/kcp-dev/kcp/issues/2706

2023-02-22 15:37 UTC, ncdc requested changes

2023-02-22 15:37 UTC, ncdc commented on docs/content/en/developers/metrics.md
> +linkTitle: "kcp Prometheus metrics"
We aren't using `linkTitle` any more

2023-02-22 15:37 UTC, ncdc commented on docs/content/en/developers/metrics.md
> +weight: 1
We aren't using `weight` any more

2023-02-22 15:37 UTC, ncdc commented on docs/content/en/developers/metrics.md
> +Inspecting Prometheus metrics of e2e runs
```suggestion
    Inspecting Prometheus metrics of e2e runs
```

2023-02-22 15:37 UTC, ncdc commented on docs/content/en/developers/metrics.md
> +# Inspecting Prometheus metrics for e2e runs
Please name the file to roughly match with this heading. mkdocs sorts based on filename. So `inspecting-metrics-for-e2e-tests` or something like that.

2023-02-22 15:37 UTC, ncdc commented on docs/content/en/developers/metrics.md
> +### Github
global: GitHub

2023-02-28 15:26 UTC, s-urbaniak commented on docs/content/en/developers/metrics.md
> +linkTitle: "kcp Prometheus metrics"
removed

2023-02-28 15:26 UTC, s-urbaniak commented on docs/content/en/developers/metrics.md
> +weight: 1
removed

2023-02-28 15:27 UTC, s-urbaniak commented on docs/content/en/developers/metrics.md
> +Inspecting Prometheus metrics of e2e runs
indented

2023-02-28 15:27 UTC, s-urbaniak commented on docs/content/en/developers/metrics.md
> +### Github
fixed

2023-02-28 16:20 UTC, merged