:sparkles:  rebase k/k 1.31 - pre-1 attempt
kcp-dev/kcp pull request #3160
Opened 2024-09-03 17:11 UTC by mjudeikis

## Summary

## Related issue(s)

Fixes #

## Release Notes

```release-note
NONE
```

2024-09-09 06:08 UTC, embik requested changes
Couple of nits, but overall looking really solid 👍🏻

2024-09-14 11:33 UTC, mjudeikis commented on pkg/cache/server/server.go
> +		if err := bootstrap.Bootstrap(klog.NewContext(ctx, logger), s.ApiExtensionsClusterClient); err != nil {
mistake

2024-09-15 14:00 UTC, embik approved these changes
/lgtm

I'd just be very happy about a PR description documenting what had to be done for the 1.31 upgrade :)

2024-09-16 16:59 UTC, mjudeikis commented
> I'd just be very happy about a PR description documenting what had to be done for the 1.31 upgrade :)

Added but needed to think what to add as it was so smooth :D

2024-09-19 06:19 UTC, embik approved these changes
/approve

2024-09-19 06:20 UTC, merged