Add front proxy
kcp-dev/kcp pull request #973
Opened 2022-05-03 16:59 UTC by kylape

This adds the front proxy into the topology of the deployment manifest.

Instead of terminating TLS at the ingress router, it will instead terminate at the front proxy, and the proxy will route requests to either KCP or the virtual workspaces process.

This also leverages cert-manager to add the ability to authenticate using a certificate.  Groups will be assigned using the organizations listed on the cert.

2022-05-03 17:05 UTC, aojea commented
does this allow to use http2 to the backend?

2022-05-03 21:26 UTC, csams commented
@aojea The backends are setup here: https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/proxy.go#L61-L68. We may need to update the `Transport` to enable http2. Would that just be setting `ForceAttemptHTTP2` to true?

2022-05-04 02:01 UTC, csams requested changes

2022-05-04 02:01 UTC, csams commented on manifest/kcp-front-proxy.yaml
> +        - --v=4
Let's change this to 6 so the proxy will log basic info about requests to the backends.

2022-05-04 02:13 UTC, kylape commented
We can try out the changes on https://github.com/kcp-dev/kcp/pull/873 with this manifest to see if http2 works.

2022-05-04 07:05 UTC, aojea commented
> @aojea The backends are setup here: https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/proxy.go#L61-L68. We may need to update the `Transport` to enable http2. Would that just be setting `ForceAttemptHTTP2` to true?

I would build the transport differently, the ReverseProxy uses http.DefaultTransport by default https://pkg.go.dev/net/http/httputil#ReverseProxy
```
// DefaultTransport is the default implementation of Transport and is
// used by DefaultClient. It establishes network connections as needed
// and caches them for reuse by subsequent calls. It uses HTTP proxies
// as directed by the $HTTP_PROXY and $NO_PROXY (or $http_proxy and
// $no_proxy) environment variables.
var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	DialContext: defaultTransportDialContext(&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
	}),
	ForceAttemptHTTP2:     true,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
```

initializing it https://github.com/kcp-dev/kcp/blob/main/pkg/proxy/proxy.go#L61-L68 this way you are overriding some sane defaults. I would initialize it as:
```go
        transport = http.DefaultTransport
        transport.TLSClientConfig = &tls.Config{
			Certificates: []tls.Certificate{cert},
			RootCAs:      caCertPool,
		},
	proxy := httputil.NewSingleHostReverseProxy(target)
	proxy.Transport = transport
```

2022-05-09 15:11 UTC, kylape commented
Note that this is checking in an Openshift-specific resource (Route).  This is a short term solution; we intend to have a more generic manifest available for the community that doesn't assume any particular distribution.

2022-05-09 15:13 UTC, merged